# Generated by Django 2.2 on 2019-04-25 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo')),
                ('number', models.IntegerField()),
                ('news', models.IntegerField()),
                ('new_number', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ico', models.ImageField(upload_to='ico')),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('pic', models.ImageField(upload_to='pic')),
                ('time', models.DateTimeField()),
                ('read', models.IntegerField()),
                ('looking', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('share', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.AccountModel')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
