# Generated by Django 2.2 on 2019-04-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionModel',
        ),
    ]
