# Generated by Django 2.2 on 2019-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_delete_functionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ico', models.ImageField(upload_to='ico')),
            ],
            options={
                'db_table': 'function',
            },
        ),
    ]
