# Generated by Django 2.2 on 2019-04-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_functionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionModel',
        ),
    ]
