# Generated by Django 2.2 on 2019-04-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_functionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'left',
            },
        ),
    ]
