# Generated by Django 2.2 on 2019-04-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_leftmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftmodel',
            name='img',
        ),
    ]
