# Generated by Django 2.2 on 2019-04-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='keepNum',
            new_name='pageNum',
        ),
    ]
