# Generated by Django 2.2 on 2019-04-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190422_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='commentNum',
        ),
    ]
