# Generated by Django 2.2 on 2019-04-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190422_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='name',
            new_name='pname',
        ),
    ]
