# Generated by Django 2.2 on 2019-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190423_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorDetail',
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(max_length=64),
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
